Code/RentingManager.Client/Models/Rent/ItemModel.cs
using RentingManager.Server.Core.Domain;
using System.Collections.Generic;

namespace RentingManager.Client.Models.Rent
{
    public class ItemModel
    {
        public ItemModel()
        {
            Rates = new List<RateModel>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public string IdetificationNumber { get; set; }

        public string ModelNumber { get; set; }

        public IList<RateModel> Rates { get; set; }

        public bool Selected { get; set; }
    }
}

Code/RentingManager.Client/Models/Rent/ItemPopupModel.cs
using RentingManager.Server.Core.Domain;
using System.Collections.Generic;

namespace RentingManager.Client.Models.Rent
{
    public class ItemPopupModel
    {
        public ItemPopupModel()
        {
            AvailableItems = new List<ItemModel>();
        }

        public IList<ItemType> AvailableItemTypes { get; set; }

        public IList<ItemModel> AvailableItems { get; set; }
    }
}

Code/RentingManager.Client/Models/Rent/RateModel.cs
namespace RentingManager.Client.Models.Rent
{
    public class RateModel
    {
        public string RentalRateType { get; set; }

        public decimal Rate { get; set; }
    }
}

Code/RentingManager.Client/Models/Rent/RentInfoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RentingManager.Client.Models.Rent
{
    public class RentInfoModel
    {
        public RentInfoModel()
        {
            ItemPopup = new ItemPopupModel();
            RentItems = new List<RentItemModel>();
        }

        public string ReferenceNumber { get; set; }

        public int CustomerId { get; set; }

        [Display(Name = "Customer Name")]
        public string CustomerName { get; set; }

        [Display(Name = "Renting Date")]
        public DateTime RentingDate { get; set; }

        [Display(Name = "Advance Payment")]
        public decimal AdvancePayment { get; set; }

        public string Description { get; set; }

        public IList<RentItemModel> RentItems { get; set; }

        public ItemPopupModel ItemPopup { get; set; }
    }
}

Code/RentingManager.Client/Models/Rent/RentItemModel.cs
using RentingManager.Server.Core.Domain;
using System;

namespace RentingManager.Client.Models.Rent
{
    public class RentItemModel
    {
        public int ItemId { get; set; }

        public string ItemName { get; set; }

        public RentalRateType RateType { get; set; }

        public decimal GivenRate { get; set; }

        public DateTime RentingDate { get; set; }
    }
}

Code/RentingManager.Client/Models/Rent/RentModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace RentingManager.Client.Models.Rent
{
    public class RentModel
    {
        public int Id { get; set; }

        public string ReferenceNumber { get; set; }

        public int CustomerId { get; set; }

        [Display(Name = "Customer Name")]
        public string CustomerName { get; set; }

        [Display(Name = "Renting Date")]
        public DateTime RentingDate { get; set; }

        [Display(Name = "Advance Payment")]
        public decimal AdvancePayment { get; set; }

        public string Description { get; set; }

    }
}

Code/RentingManager.Client/Models/Rent/RentPagedListModel.cs
using RentingManager.Client.Models.Common;
using System.Collections.Generic;

namespace RentingManager.Client.Models.Rent
{
    public class RentPagedListModel
    {
        public RentPagedListModel()
        {
            List = new List<RentModel>();
            StatusList = new List<RentStatusModel>();
        }

        public IList<RentModel> List { get; set; }

        public IList<RentStatusModel> StatusList { get; set; }

        public PagerModel PagerModel { get; set; }
    }
}

Code/RentingManager.Client/Models/Rent/RentStatusModel.cs
namespace RentingManager.Client.Models.Rent
{
    public class RentStatusModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

Code/RentingManager.Client/Models/Rent/ReturnInfoModel.cs
using RentingManager.Server.Core.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RentingManager.Client.Models.Rent
{
    public class ReturnInfoModel
    {
        public ReturnInfoModel()
        {
            ReturnItems = new List<ReturnItemModel>();
            PreviousPayments = new List<Payment>();
        }

        public int RentId { get; set; }

        public string ReferenceNumber { get; set; }

        [Display(Name = "Return Date")]
        public DateTime ReturnDate { get; set; }

        public IList<ReturnItemModel> ReturnItems { get; set; }

        public IList<Payment> PreviousPayments { get; set; }
    }
}

Code/RentingManager.Client/Models/Rent/ReturnInvoiceModel.cs
using RentingManager.Server.Core.Domain;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RentingManager.Client.Models.Rent
{
    public class ReturnInvoiceModel
    {
        [Display(Name = "Reference Number")]
        public string ReferenceNumber { get; set; }

        [Display(Name = "Customer Id")]
        public int CustomerId { get; set; }

        [Display(Name = "Customer Name")]
        public string CustomerName { get; set; }

        public IList<InvoiceItem> Items { get; set; }

        [Display(Name = "Total Amount")]
        public decimal TotalAmount { get; set; }

        [Display(Name = "Paid Amount")]
        public decimal PaidAmount { get; set; }

        [Display(Name = "Balance Amount")]
        public decimal BalanceAmount { get; set; }
    }
}

Code/RentingManager.Client/Models/Rent/ReturnItemModel.cs
using RentingManager.Server.Core.Domain;
using System;

namespace RentingManager.Client.Models.Rent
{
    public class ReturnItemModel
    {
        public int Id { get; set; }

        public int ItemId { get; set; }

        public string ItemName { get; set; }

        public RentalRateType RateType { get; set; }

        public decimal GivenRate { get; set; }

        public DateTime RentingDate { get; set; }

        public bool Returned { get; set; }
    }
}

Code/RentingManager.Client/Controllers/RentController.cs
using Microsoft.AspNetCore.Mvc;
using RentingManager.Client.Models.Common;
using RentingManager.Client.Models.Rent;
using RentingManager.Server.Core;
using RentingManager.Server.Core.Domain;
using RentingManager.Server.Services;
using System;
using System.Collections.Generic;
using System.Linq;

namespace RentingManager.Client.Controllers
{
    public class RentController : Controller
    {
        private ICustomerService _customerService;

        private IItemService _itemService;

        private IRentService _rentService;

        public RentController(ICustomerService customerService, IItemService itemService, IRentService rentService)
        {
            _customerService = customerService;
            _itemService = itemService;
            _rentService = rentService;
        }

        public IActionResult Create(int customerId, int searchTypeId)
        {
            var model = new RentInfoModel();
            model.CustomerId = customerId;
            var customer = _customerService.GetCustomer(customerId);
            if (customer != null)
            {
                model.CustomerName = customer.Name;
            }

            model.RentingDate = DateTime.Today;
            model.ItemPopup.AvailableItemTypes = _itemService.GetItemTypes();
            var defaultValue = new ItemType() { Id = 0, Name = "<Select>" };
            model.ItemPopup.AvailableItemTypes.Insert(0, defaultValue);

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(RentInfoModel model)
        {
            var rent = new Rent()
            {
                ReferenceNumber = model.ReferenceNumber,
                CustomerId = model.CustomerId,
                Description = model.Description
            };

            foreach (var rentItemModel in model.RentItems)
            {
                var rentItem = new RentItem()
                {
                    ItemId = rentItemModel.ItemId,
                    RateType = rentItemModel.RateType,
                    GivenRate = rentItemModel.GivenRate,
                    RentingDate = model.RentingDate
                };

                rent.RentItems.Add(rentItem);
            }

            rent.Payments.Add(new Payment() {
                Amount = model.AdvancePayment,
                Date = model.RentingDate,
                Description = "Advance Payment"
            });

            try
            {
                _rentService.SaveRent(rent);
                TempData["SuccessMessage"] = "Rent detail saved successfully";
                return RedirectToAction("RentList");
            }
            catch
            {
                TempData["ErrorMessage"] = "Error occured.";
                return Create(model.CustomerId, 0);
            }
        }

        public IActionResult ItemList(int searchTypeId)
        {
            var model = new List<ItemModel>();
            var items = _itemService.GetItemsWithRates(searchTypeId);
            foreach (var item in items)
            {
                var itemModel = new ItemModel
                {
                    Id = item.Id,
                    Name = item.Name,
                    IdetificationNumber = item.IdetificationNumber,
                    ModelNumber = item.ModelNumber,
                };

                foreach (RentalRate rate in item.Rates)
                {
                    var rateModel = new RateModel()
                    {
                        RentalRateType = Enum.GetName(typeof(RentalRateType), rate.RateType),
                        Rate = rate.Rate
                    };

                    itemModel.Rates.Add(rateModel);
                }
                model.Add(itemModel);
            }
            
            return Json(model);
        }

        public IActionResult RentList(int pageNumber, int customerId, int status, string refNumber)
        {
            var pageSize = 3;
            var pageIndex = 0;
            if (pageNumber > 0)
            {
                pageIndex = pageNumber - 1;
            }

            var model = new RentPagedListModel();
            foreach (var statusId in Enum.GetValues(typeof(RentStatus)))
            {
                var rentStatusModel = new RentStatusModel() {
                    Id = (int)statusId,
                    Name = Enum.GetName(typeof(RentStatus), statusId)
                };

                model.StatusList.Add(rentStatusModel);
            }

            IPagedList<Rent> rentList = _rentService.GetRentList(customerId, refNumber, status, pageIndex, pageSize);

            foreach (var rent in rentList)
            {
                var rentModel = new RentModel() {
                    Id = rent.Id,
                    ReferenceNumber = rent.ReferenceNumber,
                    CustomerId = rent.CustomerId
                };

                model.List.Add(rentModel);
            }

            model.PagerModel = new PagerModel
            {
                PageSize = rentList.PageSize,
                TotalRecords = rentList.TotalCount,
                PageIndex = rentList.PageIndex,
                ShowTotalSummary = false,
                RouteActionName = "RentList",
                UseRouteLinks = false,
                RouteValues = new RentListRouteValues
                {
                    pageNumber = pageNumber,
                    customerId = customerId,
                    refNumber = refNumber,
                    status = status
                }
            };

            return View(model);
        }

        public IActionResult Return(int id)
        {
            var rent = _rentService.GetRentWithRentItemsAndPaymentsById(id);
            ReturnInfoModel model = null;
            if (rent != null)
            {
                model = new ReturnInfoModel()
                {
                    RentId = id,
                    ReferenceNumber = rent.ReferenceNumber,
                    ReturnDate = DateTime.Today
                };

                foreach (var rentItem in rent.RentItems)
                {
                    var returnItemModel = new ReturnItemModel()
                    {
                        Id = rentItem.Id,
                        ItemId = rentItem.ItemId,
                        RateType = rentItem.RateType,
                        GivenRate = rentItem.GivenRate,
                        RentingDate = rentItem.RentingDate
                    };

                    if (rentItem.ReturnDate != DateTime.MinValue)
                    {
                        returnItemModel.Returned = true;
                    }

                    var item = _itemService.GetItem(rentItem.ItemId);
                    if (item != null)
                    {
                        returnItemModel.ItemName = item.Name;
                    }

                    model.ReturnItems.Add(returnItemModel);
                }

                model.PreviousPayments = rent.Payments;
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Return(ReturnInfoModel model)
        {
            var returnItemIds = new List<int>();
            foreach (var item in model.ReturnItems)
            {
                
                if (item.Returned && item.RentingDate == DateTime.MinValue)
                {
                    returnItemIds.Add(item.Id);
                }
            }

            if (returnItemIds.Count() > 0)
            {
                try
                {
                    _rentService.ReturnRentItems(model.RentId, model.ReturnDate, returnItemIds);
                    TempData["SuccessMessage"] = "Saved successfully";
                    return RedirectToAction("ReturnInvoice", new { rentId = model.RentId });
                }
                catch
                {
                    TempData["ErrorMessage"] = "Error occured.";
                    return View(model);
                }
            }
            else
            {
                return Return(model.RentId);
            }
        }

        public IActionResult ReturnInvoice(int rentId)
        {
            var invoiceInfo = _rentService.GetReturnInvoiceInfo(rentId);
            var model = new ReturnInvoiceModel()
            {
                ReferenceNumber = invoiceInfo.ReferenceNumber,
                CustomerId = invoiceInfo.CustomerId,
                CustomerName = invoiceInfo.CustomerName,
                Items = invoiceInfo.Items
            };

            model.TotalAmount = invoiceInfo.Items.Sum(i => i.Item.GivenRate);
            model.PaidAmount = invoiceInfo.Payments.Sum(i => i.Amount);
            model.BalanceAmount = model.TotalAmount - model.PaidAmount;

            return View(model);
        }
    }
}

Code/RentingManager.Client/Views/Rent/Create.cshtml
@model RentingManager.Client.Models.Rent.RentInfoModel

@{
    ViewData["Title"] = "Create";
}

<h2>Rent Items</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="CustomerId" value="@Model.CustomerId" />
                <label asp-for="CustomerName" class="control-label"></label>
                <label asp-for="CustomerName" class="form-control">@Model.CustomerName</label>
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReferenceNumber" class="control-label"></label>
                <input asp-for="ReferenceNumber" class="form-control" />
                <span asp-validation-for="ReferenceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RentingDate" class="control-label"></label>
                <input asp-for="RentingDate" type="date" class="form-control" />
                <span asp-validation-for="RentingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdvancePayment" class="control-label"></label>
                <input asp-for="AdvancePayment" class="form-control" />
                <span asp-validation-for="AdvancePayment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="button" value="Add Items" class="btn btn-primary" data-toggle="modal" data-target="#itemModal">Add Items</button>
            </div>
            <div>
                <br />
                <label asp-for="CustomerName" class="control-label">Items to be rented:</label>
                <br />
            </div>
            <div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Item Name
                            </th>
                            <th>
                                Rate Type
                            </th>
                            <th>
                                Rate
                            </th>
                        </tr>
                    </thead>
                    <tbody id="rentItemTableBody">
                        @for (int i = 0; i < Model.RentItems.Count(); i++)
                        {
                            <tr>
                                <td>
                                    @Html.HiddenFor(m => Model.RentItems[i].ItemId)
                                    @Html.DisplayFor(m => Model.RentItems[i].ItemName)
                                </td>
                                <td>
                                    @Html.HiddenFor(m => Model.RentItems[i].RateType)
                                    @Html.DisplayFor(m => Model.RentItems[i].RateType)
                                </td>
                                <td>
                                    @Html.HiddenFor(m => Model.RentItems[i].GivenRate)
                                    @Html.DisplayFor(m => Model.RentItems[i].GivenRate)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<div id="itemModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Select Items</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "Rent", FormMethod.Get))
                {
                    <div class="row">

                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.Label("", "Item Type", new { @class = "control-label" })
                                @Html.DropDownList("searchTypeId", new SelectList(Model.ItemPopup.AvailableItemTypes, "Id", "Name"), htmlAttributes: new { @class = "form-control" , id ="ddlSearch"})
                            </div>
                            <div class="form-group">
                                <input type="button" value="Search" class="btn btn-success" id="btnSearch"/>
                            </div>
                        </div>
                    </div>

                }

                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Item Name
                            </th>
                            <th>
                                Idetification Number
                            </th>
                            <th>
                                Model Number
                            </th>
                            <th>
                                Rate Type
                            </th>
                            <th>
                                Rate
                            </th>
                        </tr>
                    </thead>
                    <tbody id="itemTableBody">
                        
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    
    $(document).ready(function () {
        $('#btnSearch').click(function () {
            var type = $('#ddlSearch').val();
            $.get("@Url.Action("ItemList", "Rent")"
                , { searchTypeId: type }
                , function (data) {
                    $("#itemTableBody").empty();
                    $(data).each(function () {
                        $("#itemTableBody").append(
                            '<tr>' +
                            '<td id="tdName' + this.id +'"> ' + this.name + '</td>' +
                            '<td> ' + this.idetificationNumber + '</td>' +
                            '<td> ' + this.modelNumber + '</td>' +
                            '<td> ' + getRateDropDownList(this.rates, this.id) + '</td>' +
                            '<td><input type="text" value="' + this.rates[0].rate + '" id = "txt' + this.id + '" class="form-control"/></td>' +
                            '<td><input type="button" value="+" onclick="addItem(' + this.id +')" class = "btn btn-primary"/></td>' +
                            '</tr>'
                        );
                    });

                    $('.ddlRates').change(function () {
                        var textBoxId = "txt" + $(this).attr('id').replace('ddl', '');
                        $('#' + textBoxId).val($(this).val());
                    });
            });
        });
    });

    function getRateDropDownList(rates, itemId) {
        var html = '<select class="ddlRates form-control" id = "ddl' + itemId +'">';
        $(rates).each(function () {
            html = html + '<option value="' + this.rate + '">' + this.rentalRateType + '</option>';
        });

        html = html + '</select>';

        return html;
    }

    var rowIndex = 0;

    function addItem(itemId) {
        var name = $('#tdName' + itemId).text();
        var rateType = $('#ddl' + itemId + ' :selected').text();
        var rate = $('#txt' + itemId).val();
        $("#rentItemTableBody").append(
            '<tr id="trRentItemTable' + itemId + '">' +
            '<td> <input type="hidden" name="RentItems[' + rowIndex + '].ItemId" id="RentItems_' + rowIndex +'__ItemId" value="' + itemId + '"/>' +
             name +
            '</td>' +
            '<td> <input type="hidden" name="RentItems[' + rowIndex + '].RateType" id="RentItems_' + rowIndex +'__RateType" value="' + rateType + '"/>' +
            rateType + '</td>' +
            '<td> <input type="hidden" name="RentItems[' + rowIndex + '].GivenRate" id="RentItems_' + rowIndex +'__GivenRate" value="' + rate + '"/>' +
            rate + '</td>' +
            '<td><input type="button" value="-" onclick="removeItem(' + itemId + ')" class = "btn btn-primary"/></td>' +
            '</tr> '
        );

        rowIndex++;
    }

    function removeItem(itemId) {
        $("#trRentItemTable" + itemId).remove();
    }

</script>

Code/RentingManager.Client/Views/Rent/RentList.cshtml
@using RentingManager.Client.Extensions
@model RentingManager.Client.Models.Rent.RentPagedListModel

@{
    ViewData["Title"] = "RentList";
}

<h2>RentList</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

@using (Html.BeginForm("RentList", "Rent", FormMethod.Get))
{
    <div class="row">

        <div class="col-md-4">
            <div class="form-group">
                @Html.Label("", "Status", new { @class = "control-label" })
                @Html.DropDownList("status", new SelectList(Model.StatusList, "Id", "Name"), htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.Label("", "Reference Number", new { @class = "control-label" })
                @Html.TextBox("refNumber", null, "", new { @class = "form-control input-md" })
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>

}

<table class="table">
    <thead>
        <tr>
            <th>Reference Number</th>

            <th>Customer</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.List)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m => item.ReferenceNumber)
                </td>
                <td>
                    @Html.DisplayFor(m => item.CustomerId)
                </td>
                <td>
                    @Html.ActionLink("View/Return", "Return", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var pager = Html.Pager(Model.PagerModel);
}
@if (!string.IsNullOrEmpty(pager.ToHtmlString()))
{
    <div class="pager">
        @pager
    </div>
}

Code/RentingManager.Client/Views/Rent/Return.cshtml
@model RentingManager.Client.Models.Rent.ReturnInfoModel

@{
    ViewData["Title"] = "Return";
}

<h2>Return</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Return">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="RentId" />
                <label asp-for="ReferenceNumber" class="control-label"></label>
                <input asp-for="ReferenceNumber" class="form-control" />
                <span asp-validation-for="ReferenceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" type="date" class="form-control" />
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
            @if (Model.PreviousPayments.Count() > 0)
            {
                <div>
                    Previous Payments
                </div>
                <div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Amount</th>

                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.PreviousPayments)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(m => item.Amount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(m => item.Date)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }

            <div>
                Rented Items
            </div>
            <div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Item Name</th>

                            <th>Rate Type</th>

                            <th>Given Rate</th>

                            <th>Renting Date</th>

                            <th>Return</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.ReturnItems.Count(); i++)
                        {
                            <tr>
                                <td>
                                    @Html.HiddenFor(m => Model.ReturnItems[i].Id)
                                    @Html.DisplayFor(m => Model.ReturnItems[i].ItemName)
                                </td>
                                <td>
                                    @Html.DisplayFor(m => Model.ReturnItems[i].RateType)
                                </td>
                                <td>
                                    @Html.DisplayFor(m => Model.ReturnItems[i].GivenRate)
                                </td>
                                <td>
                                    @Html.DisplayFor(m => Model.ReturnItems[i].RentingDate)
                                </td>
                                <td>
                                    @if (Model.ReturnItems[i].Returned)
                                    {
                                        @Html.CheckBoxFor(m => Model.ReturnItems[i].Returned, new { @disabled = "disabled" , @checked= "checked"})
                                    }
                                    else
                                    {
                                        @Html.CheckBoxFor(m => Model.ReturnItems[i].Returned)
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}