Code/RentingManager.Client/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using RentingManager.Client.Models.Common;
using RentingManager.Client.Models.Customer;
using RentingManager.Server.Core;
using RentingManager.Server.Core.Domain;
using RentingManager.Server.Services;
using System.Collections.Generic;

namespace RentingManager.Client.Controllers
{
    public class CustomerController : Controller
    {
        private ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CustomerInfoModel model)
        {
            var customer = new Customer()
            {
                Name = model.Name.Trim(),
                Nic = model.Nic.Trim(),
                AddressLine1 = model.AddressLine1.Trim(),
                AddressLine2 = model.AddressLine2.Trim(),
                AddressLine3 = model.AddressLine3.Trim()
            };

            try
            {
                _customerService.SaveCustomer(customer);
                TempData["SuccessMessage"] = "Customer saved successfully";
                return RedirectToAction("CustomerList");

            }
            catch
            {
                TempData["ErrorMessage"] = "Error occured.";
            }
            
            return View();
        }

        public ActionResult CustomerList(int pageNumber, string searchByNicString, string searchByNameString)
        {
            var pageSize = 2;
            var pageIndex = 0;
            if (pageNumber > 0)
            {
                pageIndex = pageNumber - 1;
            }
            
            CustomerInfoPagedListModel model = new CustomerInfoPagedListModel();
            IPagedList<Customer> customers = _customerService.GetCustomers(searchByNicString?.Trim(), searchByNameString?.Trim(), pageIndex, pageSize);
            foreach (var customer in customers)
            {
                CustomerInfoModel customerInfoModel = new CustomerInfoModel()
                {
                    Id = customer.Id,
                    Name = customer.Name,
                    Nic = customer.Nic,
                    AddressLine1 = customer.AddressLine1,
                    AddressLine2 = customer.AddressLine2,
                    AddressLine3 = customer.AddressLine3
                };

                model.List.Add(customerInfoModel);
            }

            model.PagerModel = new PagerModel
            {
                PageSize = customers.PageSize,
                TotalRecords = customers.TotalCount,
                PageIndex = customers.PageIndex,
                ShowTotalSummary = false,
                RouteActionName = "CustomerList",
                UseRouteLinks = false,
                RouteValues = new CustomerListRouteValues { pageNumber = pageNumber
                        , searchByNicString = searchByNicString, searchByNameString = searchByNameString }
            };

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            IList<CustomerInfoModel> model = new List<CustomerInfoModel>();
            Customer customer = _customerService.GetCustomer(id);
            CustomerInfoModel customerInfoModel = new CustomerInfoModel()
            {
                Id = customer.Id,
                Name = customer.Name,
                Nic = customer.Nic,
                AddressLine1 = customer.AddressLine1,
                AddressLine2 = customer.AddressLine2,
                AddressLine3 = customer.AddressLine3
            };

            return View(customerInfoModel);
        }

        [HttpPost]
        public ActionResult Edit(CustomerInfoModel model)
        {
            var customer = new Customer()
            {
                Id = model.Id,
                Name = model.Name.Trim(),
                Nic = model.Nic.Trim(),
                AddressLine1 = model.AddressLine1.Trim(),
                AddressLine2 = model.AddressLine2.Trim(),
                AddressLine3 = model.AddressLine3.Trim()
            };

            try
            {
                _customerService.UpdateCustomer(customer);
                TempData["SuccessMessage"] = "Customer updated successfully";
                return RedirectToAction("CustomerList");

            }
            catch
            {
                TempData["ErrorMessage"] = "Error occured.";
            }
            
            return View();
        }

        public ActionResult Delete(int id)
        {
            try
            {
                _customerService.DeleteCustomer(id);
                TempData["SuccessMessage"] = "Customer deleted successfully";
                return RedirectToAction("CustomerList");

            }
            catch
            {
                TempData["ErrorMessage"] = "Error occured.";
                return View();
            }
        }
    }
}

Code/RentingManager.Client/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using RentingManager.Client.Models.Common;
using RentingManager.Client.Models.Item;
using RentingManager.Server.Core;
using RentingManager.Server.Core.Domain;
using RentingManager.Server.Services;
using System;
using System.Collections.Generic;

namespace RentingManager.Client.Controllers
{
    public class ItemController : Controller
    {
        IItemService _itemService;

        public ItemController(IItemService itemService)
        {
            _itemService = itemService;
        }

        public IActionResult CreateType()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateType(ItemTypeModel model)
        {
            ItemType type = new ItemType()
            {
                Name = model.Name.Trim(),
                Description = model.Description.Trim()
            };

            try
            {
                _itemService.SaveItemType(type);
                TempData["SuccessMessage"] = "Item type saved successfully";
                return RedirectToAction("ItemTypeList");
            }
            catch
            {
                TempData["ErrorMessage"] = "Error occured.";
                return View();
            }
        }

        public ActionResult EditType(int id)
        {
            IList<ItemTypeModel> model = new List<ItemTypeModel>();
            var itemType = _itemService.GetItemType(id);
            var itemTypeModel = new ItemTypeModel()
            {
                Id = itemType.Id,
                Name = itemType.Name,
                Description = itemType.Description
            };

            return View(itemTypeModel);
        }

        [HttpPost]
        public ActionResult EditType(ItemTypeModel model)
        {
            var itemType = new ItemType()
            {
                Id = model.Id,
                Name = model.Name.Trim(),
                Description = model.Description.Trim()
            };

            try
            {
                _itemService.UpdateItemtype(itemType);
                TempData["SuccessMessage"] = "Item type updated successfully";
                return RedirectToAction("ItemTypeList");

            }
            catch
            {
                TempData["ErrorMessage"] = "Error occured.";
            }

            return View();
        }

        public ActionResult DeleteType(int id)
        {
            try
            {
                _itemService.DeleteItemType(id);
                TempData["SuccessMessage"] = "Item type deleted successfully";
                return RedirectToAction("ItemTypeList");

            }
            catch
            {
                TempData["ErrorMessage"] = "Error occured.";
                return RedirectToAction("ItemTypeList");
            }
        }

        public IActionResult ItemTypeList(int pageNumber, string searchByNameString)
        {
            var pageSize = 2;
            var pageIndex = 0;
            if (pageNumber > 0)
            {
                pageIndex = pageNumber - 1;
            }

            ItemTypePagedListModel model = new ItemTypePagedListModel();
            IPagedList<ItemType> itemTypes = _itemService.GetItemTypes(searchByNameString?.Trim(), pageIndex, pageSize);
            foreach (var itemType in itemTypes)
            {
                ItemTypeModel itemTypeModel = new ItemTypeModel()
                {
                    Id = itemType.Id,
                    Name = itemType.Name,
                    Description = itemType.Description
                };

                model.List.Add(itemTypeModel);
            }

            model.PagerModel = new PagerModel
            {
                PageSize = itemTypes.PageSize,
                TotalRecords = itemTypes.TotalCount,
                PageIndex = itemTypes.PageIndex,
                ShowTotalSummary = false,
                RouteActionName = "ItemTypeList",
                UseRouteLinks = false,
                RouteValues = new ItemTypeListRouteValues
                {
                    pageNumber = pageNumber,
                    searchByNameString = searchByNameString
                }
            };

            return View(model);
        }

        public IActionResult CreateItem()
        {
            var model = new ItemInfoModel();
            foreach (var name in Enum.GetNames(typeof(RentalRateType)))
            {
                model.Rates.Add(new RentalRateModel() { RentalRateType = name, DisplayLabel = string.Format("{0} Rate", name) });
            }

            model.AvailableItemTypes = _itemService.GetItemTypes(string.Empty);
            var defaultValue = new ItemType() { Id = 0, Name = "<Select>" };
            model.AvailableItemTypes.Insert(0, defaultValue);

            return View(model);
        }

        [HttpPost]
        public IActionResult CreateItem(ItemInfoModel model)
        {
            var item = new Item();
            item.Name = model.Name;
            item.ModelNumber = model.ModelNumber;
            item.IdetificationNumber = model.IdetificationNumber;
            item.TypeId = model.SelectedItemTypeId;
            item.Description = model.Description;
            foreach (var rateModel in model.Rates)
            {
                var rate = new RentalRate()
                {
                    RateType = Enum.Parse<RentalRateType>(rateModel.RentalRateType),
                    Rate = rateModel.Rate
                };

                item.Rates.Add(rate);
            }

            try
            {
                _itemService.SaveItem(item);
                TempData["SuccessMessage"] = "Item saved successfully";
                return RedirectToAction("ItemList");
            }
            catch
            {
                TempData["ErrorMessage"] = "Error occured.";
                return CreateItem();
            }
        }

        public IActionResult ItemList(int pageNumber, int searchTypeId, string searchName, string searchIdentification, string searchModelNumber)
        {
            var pageSize = 3;
            var pageIndex = 0;
            if (pageNumber > 0)
            {
                pageIndex = pageNumber - 1;
            }

            IPagedList<Item> items = _itemService.GetItems(searchTypeId, searchName, searchIdentification, searchModelNumber, pageIndex, pageSize);
            ItemPagedListModel model = new ItemPagedListModel();
            foreach (var item in items)
            {
                var itemModel = new ItemModel
                {
                    Id = item.Id,
                    Name = item.Name,
                    IdetificationNumber = item.IdetificationNumber,
                    ModelNumber = item.ModelNumber
                };

                model.List.Add(itemModel);
            }

            if (model.AvailableItemTypes == null)
            {
                model.AvailableItemTypes = _itemService.GetItemTypes();
                var defaultValue = new ItemType() { Id = 0, Name = "<Select>" };
                model.AvailableItemTypes.Insert(0, defaultValue);
            }

            model.PagerModel = new PagerModel
            {
                PageSize = items.PageSize,
                TotalRecords = items.TotalCount,
                PageIndex = items.PageIndex,
                ShowTotalSummary = false,
                RouteActionName = "ItemList",
                UseRouteLinks = false,
                RouteValues = new ItemListRouteValues
                {
                    searchTypeId = searchTypeId,
                    pageNumber = pageNumber,
                    searchName = searchName,
                    searchModelNumber = searchModelNumber
                }
            };

            return View(model);
        }

        public ActionResult EditItem(int id)
        {
            var item = _itemService.GetItemsWithRatesById(id);
            var model = new ItemInfoModel();
            if (item != null)
            {
                model.Id = item.Id;
                model.SelectedItemTypeId = item.TypeId;
                model.Name = item.Name;
                model.IdetificationNumber = item.IdetificationNumber;
                model.ModelNumber = item.ModelNumber;
                model.Description = item.Description;

                model.AvailableItemTypes = _itemService.GetItemTypes(string.Empty);
                var defaultValue = new ItemType() { Id = 0, Name = "<Select>" };
                model.AvailableItemTypes.Insert(0, defaultValue);

                string rateTypeName;
                foreach (RentalRate rate in item.Rates)
                {
                    rateTypeName = Enum.GetName(typeof(RentalRateType), rate.RateType);
                    var rateModel = new RentalRateModel()
                    {
                        Id = rate.Id,
                        RentalRateType = rateTypeName,
                        Rate = rate.Rate,
                        DisplayLabel = string.Format("{0} Rate", rateTypeName)
                    };

                    model.Rates.Add(rateModel);
                }
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult EditItem(ItemInfoModel model)
        {
            var item = new Item
            {
                Id = model.Id,
                Name = model.Name,
                ModelNumber = model.ModelNumber,
                IdetificationNumber = model.IdetificationNumber,
                TypeId = model.SelectedItemTypeId,
                Description = model.Description
            };

            foreach (var rateModel in model.Rates)
            {
                var rate = new RentalRate()
                {
                    Id = rateModel.Id,
                    ItemId = model.Id,
                    RateType = Enum.Parse<RentalRateType>(rateModel.RentalRateType),
                    Rate = rateModel.Rate
                };

Code/RentingManager.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Renting Manager</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["SuccessMessage"]
        </div>
    }
    else if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["ErrorMessage"]
        </div>
    }
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Renting Manager</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Customer <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Customer" asp-action="Create">Add</a></li>
                            <li><a asp-area="" asp-controller="Customer" asp-action="CustomerList">List</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Item Type<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Item" asp-action="CreateType">Add Type</a></li>
                            <li><a asp-area="" asp-controller="Item" asp-action="ItemTypeList">List</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Item <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Item" asp-action="CreateItem">Add Item</a></li>
                            <li><a asp-area="" asp-controller="Item" asp-action="ItemList">List</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Rent <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Rent" asp-action="RentList">List</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - RentingManager.Client</p>
        </footer>
    </div>

    

    @RenderSection("Scripts", required: false)
</body>
</html>